### ISSUE TITLE
用ESC列印中文有亂碼

### ISSUE THREAD

**Issue by EthanChouTW** [gmfe/react-native-gm-bluetooth#1]
你好 請教一下～
我用
`GMBluetooth.writeTextToDevice('\u6f22\u5b57');`
`GMBluetooth.writeHexToDevice('\u6f22\u5b57');`
`GMBluetooth.writeTextToDevice('漢字');`

都會出現亂碼，請問我需要在config做什麼額外配置嗎？
TSC有時會是亂碼，有時不會

**Comment by liyatang** [comment]
i

**Comment by EthanChouTW** [comment]
Hi 請問是什麼原因呢？
